services:
  mongodb:
    image: mongo
    env_file:
      - .env
    ports:
      - "${EXTERNAL_PORT:-27017}:27017"
    extra_hosts:
      - 'host.docker.internal,${EXTRA_HOSTS}:host-gateway'
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-P4ssw0rdS3cur3}
    restart: always
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "'db.runCommand(\"ping\").ok'", "--quiet" ]
      interval: 30s
      timeout: 20s
      retries: 3